name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Maven
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Show Maven version
      - name: Maven Version
        run: mvn -v

      # List files (same as 'ls')
      - name: List Files
        run: ls -al

      # Build the application
      - name: Build with Maven
        run: mvn clean package

